apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wg-easy.fullname" . }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
data: 
{{- if .Values.wireguard.config }}
{{ toYaml .Values.wireguard.config | indent 2 }}
{{- end }}
  WG_HOST: {{ default (.Values.ingress.hosts | first) .Values.wireguard.config.hostname }}