{{- $fullName := include "wg-easy.fullname" . -}}
{{- if .Values.web.config.password }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}"
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.web.config.password | b64enc | quote }}
{{- end }}
