{{ if gt .Values.replicaCount 1.0 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kea-dhcp.fullname" . }}
  labels:
    {{- include "kea-dhcp.labels" . | nindent 4 }}
  {{- with .Values.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "kea-dhcp.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kea-dhcp.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}