apiVersion: v1
kind: Service
metadata:
  name: {{ include "kea-dhcp.fullname" . }}-headless
  labels:
    {{- include "kea-dhcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 67
      targetPort: dhcp
      protocol: UDP
      name: dhcp
    - port: 8080
      targetPort: control-agent
      protocol: TCP
      name: control-agent
  selector:
    {{- include "kea-dhcp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kea-dhcp.fullname" . }}
  labels:
    {{- include "kea-dhcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.dhcp.type }}
  ports:
    - port: {{ .Values.service.dhcp.port }}
      targetPort: dhcp
      protocol: UDP
      name: dhcp
  selector:
    {{- include "kea-dhcp.selectorLabels" . | nindent 4 }}
---
{{- if .Values.kea.ctrlagent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kea-dhcp.fullname" . }}-ctrl
  labels:
    {{- include "kea-dhcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ctrl.type }}
  ports:
    - port: {{ .Values.service.ctrl.port }}
      targetPort: control-agent
      protocol: TCP
      name: control-agent
  selector:
    {{- include "kea-dhcp.selectorLabels" . | nindent 4 }}
{{- end }}