image:
  repository: subspacecommunity/subspace
  pullPolicy: Always

subspace:
  ipv4pool: "10.99.97.0/24"
  ipv6pool: "fd00::10:97:0/112"
  nameservers: "1.1.1.1,1.0.0.1"
  #A record pointing to wireguard LB or NODEPORT
  endpoint: "wg.oke.byvko.dev"


persistence:
  enabled: false
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  size: 100Mi
  annotations: {}
  accessModes:
    - ReadWriteOnce
  subPath: ""

## You should use ingress for subspace
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts: [wireguard.oke.byvko.dev]
  tls:
  - hosts:
    - wireguard.oke.byvko.dev
    secretName: wireguard-tls-cert

# This must be enabled when using subspace due to the rights that iptables will need in the subspace pods.
privileged:
  enabled: true

# This will adjust the replicas that are deployed as a part of the subspace deployment.
# This is '1' by default. Your subspace cluster number will be affected by this.
replicas: 1

# If 'type' here is 'LoadBalancer', these annotations are necessary to properly use an ELB if deploying this chart in AWS, so they'll automatically get used.
# Be sure to add the appropriate domain name, cert ARN, and ssl-negotiation-policy (a default is used here).
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wg.oke.byvko.dev.
  externalTrafficPolicy: Local
  type: LoadBalancer

# Change these as you see fit.
ports:
  wireguard: 51820

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}